### ISSUE TITLE
some questions about the algorithm's requirements

### ISSUE THREAD

**Issue by sontung** [midjji/pnp#6]
Hi,
Thanks for sharing a great work. I am having trouble trying to use your algorithm, likely because I did not get all the requirements. I usually use the pose solver from opencv with _pixel coordinates_ and _intrinsic matrix_, however, the same inputs did not work with your algorithm. I would like to clarify:
1. how do we convert _pixel coordinates_ (i.e., indices of the image matrix) to the compatible inputs of your algorithm?
2. how do we input the _camera intrinsic matrix_?

Thanks again.

**Comment by midjji** [comment]
Hi,
The algorithm uses pinhole normalized coordinates.

So the input should be yn which is created using inverse(K)y

And undistorted if required.

**Comment by sontung** [comment]
Worked like charm! Thanks again for sharing this great work.
